<?php

define('CONFIG_APP_NAME', 'app.name');
define('STATUS_CODE_OK', 200);
define('STATUS_CODE_CREATE', 201);
define('STATUS_CODE_ACCEPTED', 202);
define('STATUS_CODE_UPDATE', 200);
define('STATUS_CODE_DELETE', 200);
define('STATUS_CODE_BADREQUEST', 400);
define('STATUS_CODE_NOTFOUND', 404);
define('STATUS_CODE_NOTAUTHORISED', 401);
define('STATUS_CODE_FORBIDDEN', 403);
define('STATUS_CODE_UNPROCESSABLE', 422);
define('STATUS_CODE_REDIRECTED', 302);
define('LOCALHOST', '127.0.0.1');
